version: "3"
services:
  postgres:
    image: postgres:11.4
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: testdb
